<?php

use App\Ai\Text\Contracts\TextRoleGenerator;
use App\Ai\Text\Exceptions\TextGenerationRoleException;
use App\Ai\Text\TextGenerationRequest;
use App\Ai\Text\TextRoleAgent;
use App\Ai\Text\TextRoleManager;
use App\Enums\AiAuditEvent;
use App\Enums\AiModelMode;
use App\Enums\AiModelPurpose;
use App\Enums\TextGenerationRole;
use App\Exceptions\PaidAiUnavailable;
use App\Models\AiAccountSetting;
use App\Models\AiModelPreference;
use App\Models\AiOperationAudit;
use App\Models\AiProviderCredential;
use App\Models\User;
use App\Services\Ai\ByokHttpFactory;
use App\Services\Ai\ByokOpenRouterProviderFactory;
use Illuminate\Http\Client\ConnectionException;
use Illuminate\Http\Client\Events\ConnectionFailed;
use Illuminate\Http\Client\Events\RequestSending;
use Illuminate\Http\Client\Events\ResponseReceived;
use Illuminate\Http\Client\Request;
use Illuminate\Support\Facades\Event;
use Illuminate\Support\Facades\Http;
use Illuminate\Support\Facades\Log;
use Laravel\Ai\Events\AgentPrompted;
use Laravel\Ai\Events\PromptingAgent;
use Laravel\Ai\Prompts\AgentPrompt;

beforeEach(function () {
    config([
        'ai.providers.openrouter.key' => 'test-key',
        'ai.providers.groq.key' => 'test-key',
        'text-generation.version' => 'test-v1',
        'text-generation.roles.classifier.provider' => 'openrouter',
        'text-generation.roles.classifier.model' => 'openrouter/auto',
        'text-generation.roles.classifier.timeout' => 12,
        'text-generation.roles.classifier.provider_options' => [
            'provider' => [
                'max_price' => ['prompt' => 1.0, 'completion' => 2.0],
            ],
        ],
        'text-generation.roles.classifier.fallbacks' => [
            ['provider' => 'groq', 'model' => 'llama-test', 'timeout' => 7],
        ],
    ]);
});

test('text roles resolve provider model and fallback config', function () {
    $profile = app(TextRoleManager::class)->resolve(TextGenerationRole::Classifier);

    expect($profile->role)->toBe(TextGenerationRole::Classifier)
        ->and($profile->configVersion)->toBe('test-v1')
        ->and($profile->candidates)->toBe([
            [
                'provider' => 'openrouter',
                'model' => 'openrouter/auto',
                'timeout' => 12,
                'providerOptions' => ['provider' => ['max_price' => ['prompt' => 1.0, 'completion' => 2.0]]],
            ],
            [
                'provider' => 'groq',
                'model' => 'llama-test',
                'timeout' => 7,
                'providerOptions' => [],
            ],
        ]);
});

test('missing role config fails before prompting', function () {
    config(['text-generation.roles.classifier.model' => null]);

    app(TextRoleManager::class)->resolve(TextGenerationRole::Classifier);
})->throws(TextGenerationRoleException::class, 'model');

test('role generation falls back to the next configured provider', function () {
    Log::spy();

    TextRoleAgent::fake(function (string $prompt, $attachments, $provider, string $model) {
        if ($provider->name() === 'openrouter') {
            throw new RuntimeException('private provider response content');
        }

        return "Generated by {$provider->name()} using {$model}: {$prompt}";
    });

    $result = app(TextRoleManager::class)->generate(TextGenerationRequest::make(
        TextGenerationRole::Classifier,
        'Classify this company.',
        ['industry' => 'countertops'],
        User::factory()->create(),
    ));

    expect($result->text)->toContain('Generated by groq using llama-test')
        ->and($result->provider)->toBe('groq')
        ->and($result->model)->toBe('llama-test')
        ->and($result->configVersion)->toBe('test-v1');

    TextRoleAgent::assertPrompted(fn ($prompt): bool => str_contains($prompt->prompt, '"industry": "countertops"'));

    Log::shouldHaveReceived('warning')
        ->once()
        ->with('Text generation role candidate failed; trying fallback if available.', [
            'role' => TextGenerationRole::Classifier->value,
            'provider' => 'openrouter',
            'model' => 'openrouter/auto',
            'exception_class' => RuntimeException::class,
        ]);
});

test('provider failure details are not chained into the public role exception', function () {
    TextRoleAgent::fake(fn () => throw new RuntimeException('private provider response content'));

    try {
        app(TextRoleManager::class)->generate(TextGenerationRequest::make(
            TextGenerationRole::Classifier,
            'Classify this company.',
            user: User::factory()->create(),
        ));

        test()->fail('Expected every configured provider to fail.');
    } catch (TextGenerationRoleException $exception) {
        expect($exception->getMessage())->not->toContain('private provider response content')
            ->and($exception->getPrevious())->toBeNull();
    }
});

test('role responses can be faked through the app contract', function () {
    $fake = TextRoleManager::fake([
        TextGenerationRole::AdvisorAnswer->value => 'Use a payroll provider before employee one starts.',
    ])->preventStrayPrompts();

    $result = app(TextRoleGenerator::class)->generate(TextGenerationRequest::make(
        TextGenerationRole::AdvisorAnswer,
        'What should I do before hiring?',
    ));

    expect($result->text)->toBe('Use a payroll provider before employee one starts.')
        ->and($result->provider)->toBe('fake');

    $fake->assertGenerated(TextGenerationRole::AdvisorAnswer)
        ->assertNotGenerated(TextGenerationRole::BrandCopy);
});

test('marketing roles include the human voice guidance', function () {
    TextRoleAgent::fake(['human copy']);

    app(TextRoleManager::class)->generate(TextGenerationRequest::make(
        TextGenerationRole::BrandCopy,
        'Write a homepage tagline.',
        user: User::factory()->create(),
    ));

    TextRoleAgent::assertPrompted(fn ($prompt): bool => str_contains($prompt->agent->instructions(), 'Human voice guidance')
        && str_contains($prompt->agent->instructions(), 'Avoid inflated AI-style words'));
});

test('openrouter auto candidates send their configured price caps', function () {
    Http::fake([
        'openrouter.ai/api/v1/chat/completions' => Http::response([
            'choices' => [[
                'message' => ['content' => 'classified'],
                'finish_reason' => 'stop',
            ]],
            'usage' => ['prompt_tokens' => 1, 'completion_tokens' => 1],
        ]),
    ]);

    $result = app(TextRoleManager::class)->generate(TextGenerationRequest::make(
        TextGenerationRole::Classifier,
        'Classify this company.',
        user: User::factory()->create(),
    ));

    expect($result->text)->toBe('classified');

    Http::assertSent(fn (Request $request): bool => $request->data()['model'] === 'openrouter/auto'
        && $request->data()['provider'] === [
            'max_price' => ['prompt' => 1.0, 'completion' => 2.0],
        ]);
});

test('BYOK text routing follows ordered models records actual usage and emits no global AI events', function () {
    $user = User::factory()->create();
    AiAccountSetting::factory()->for($user)->create(['byok_enabled' => true]);
    $credential = AiProviderCredential::factory()->for($user)->create([
        'secret' => 'sk-or-v1-isolated-user-secret-key',
        'fingerprint' => str_repeat('b', 64),
    ]);
    AiModelPreference::factory()->for($user)->create([
        'purpose' => AiModelPurpose::ShortText,
        'mode' => AiModelMode::Custom,
        'model_ids' => ['vendor/first-model', 'vendor/second-model'],
    ]);
    Event::fake([PromptingAgent::class, AgentPrompted::class, RequestSending::class, ResponseReceived::class]);
    $http = app(ByokHttpFactory::class);
    $http->fakeSequence()
        ->push(['error' => ['message' => 'first failed']], 500)
        ->push([
            'model' => 'vendor/second-model',
            'choices' => [[
                'message' => ['content' => 'classified'],
                'finish_reason' => 'stop',
            ]],
            'usage' => ['prompt_tokens' => 11, 'completion_tokens' => 7, 'cost' => 0.004321],
        ]);

    $result = app(TextRoleManager::class)->generate(TextGenerationRequest::make(
        TextGenerationRole::Classifier,
        'Classify this company.',
        user: $user,
    ));

    $audits = AiOperationAudit::query()->where('account_id', $user->id)->orderBy('id')->get();
    $models = collect($http->recorded())->map(fn (array $entry): string => (string) $entry[0]->data()['model'])->all();

    expect($models)->toBe(['vendor/first-model', 'vendor/second-model'])
        ->and($result->model)->toBe('vendor/second-model')
        ->and($audits->pluck('event')->all())->toBe([
            AiAuditEvent::Started,
            AiAuditEvent::Failed,
            AiAuditEvent::Started,
            AiAuditEvent::Succeeded,
        ])
        ->and($audits->last()->credential_fingerprint)->toBe($credential->fingerprint)
        ->and($audits->last()->input_tokens)->toBe(11)
        ->and($audits->last()->output_tokens)->toBe(7)
        ->and((float) $audits->last()->cost_usd)->toBe(0.004321);

    Event::assertNotDispatched(PromptingAgent::class);
    Event::assertNotDispatched(AgentPrompted::class);
    Event::assertNotDispatched(RequestSending::class);
    Event::assertNotDispatched(ResponseReceived::class);
});

test('isolated BYOK providers parse OpenRouter usage without global AI or HTTP events', function () {
    Event::fake([PromptingAgent::class, AgentPrompted::class, RequestSending::class, ResponseReceived::class]);
    app(ByokHttpFactory::class)->fake([
        'openrouter.ai/api/v1/chat/completions' => Http::response([
            'model' => 'vendor/model',
            'choices' => [[
                'message' => ['content' => 'ok'],
                'finish_reason' => 'stop',
            ]],
            'usage' => ['prompt_tokens' => 2, 'completion_tokens' => 1, 'cost' => 0.001],
        ]),
    ]);
    $agent = new TextRoleAgent('Classify.');
    $provider = app(ByokOpenRouterProviderFactory::class)->make('sk-or-v1-isolated-test-key');

    $response = $provider->prompt(new AgentPrompt($agent, 'Prompt', [], $provider, 'vendor/model', 10));

    expect($response->text)->toBe('ok');
    Event::assertNotDispatched(PromptingAgent::class);
    Event::assertNotDispatched(AgentPrompted::class);
    Event::assertNotDispatched(RequestSending::class);
    Event::assertNotDispatched(ResponseReceived::class);
});

test('isolated BYOK provider connection failures emit no global HTTP events', function () {
    Event::fake([RequestSending::class, ConnectionFailed::class]);
    app(ByokHttpFactory::class)->fake([
        'openrouter.ai/api/v1/chat/completions' => ByokHttpFactory::failedConnection(),
    ]);
    $agent = new TextRoleAgent('Classify.');
    $provider = app(ByokOpenRouterProviderFactory::class)->make('sk-or-v1-isolated-test-key');

    expect(fn () => $provider->prompt(new AgentPrompt($agent, 'Prompt', [], $provider, 'vendor/model', 10)))
        ->toThrow(ConnectionException::class);

    Event::assertNotDispatched(RequestSending::class);
    Event::assertNotDispatched(ConnectionFailed::class);
});

test('known BYOK text models honor account budgets using conservative estimates', function () {
    $user = User::factory()->create();
    AiAccountSetting::factory()->for($user)->create([
        'byok_enabled' => true,
        'monthly_usd_limit' => 0.20,
        'per_operation_usd_limit' => 0.11,
    ]);
    AiProviderCredential::factory()->for($user)->create(['secret' => 'sk-or-v1-budget-key']);
    AiModelPreference::factory()->for($user)->create([
        'purpose' => AiModelPurpose::ShortText,
        'mode' => AiModelMode::Custom,
        'model_ids' => ['openrouter/auto'],
    ]);
    $http = app(ByokHttpFactory::class);
    $http->fake([
        'openrouter.ai/api/v1/chat/completions' => Http::response([
            'model' => 'openrouter/auto',
            'choices' => [[
                'message' => ['content' => 'classified'],
                'finish_reason' => 'stop',
            ]],
            'usage' => ['prompt_tokens' => 10, 'completion_tokens' => 5, 'cost' => 0.03],
        ]),
    ]);

    $result = app(TextRoleManager::class)->generate(TextGenerationRequest::make(
        TextGenerationRole::Classifier,
        'Classify this company.',
        user: $user,
    ));

    expect($result->text)->toBe('classified')
        ->and((float) AiOperationAudit::query()->where('event', AiAuditEvent::Started->value)->sole()->cost_usd)->toBe(0.10)
        ->and((float) AiOperationAudit::query()->where('event', AiAuditEvent::Succeeded->value)->sole()->cost_usd)->toBe(0.03);

    $user->aiAccountSetting()->update(['per_operation_usd_limit' => 0.05]);

    expect(fn () => app(TextRoleManager::class)->generate(TextGenerationRequest::make(
        TextGenerationRole::Classifier,
        'Classify another company.',
        user: $user,
    )))->toThrow(PaidAiUnavailable::class);

    expect($http->recorded())->toHaveCount(1);
});
