<?php

use App\Ai\Text\Contracts\TextRoleGenerator;
use App\Ai\Text\Exceptions\TextGenerationRoleException;
use App\Ai\Text\TextGenerationRequest;
use App\Ai\Text\TextRoleManager;
use App\Enums\TextGenerationRole;
use Laravel\Ai\AnonymousAgent;

beforeEach(function () {
    config([
        'ai.providers.openrouter.key' => 'test-key',
        'ai.providers.groq.key' => 'test-key',
        'text-generation.version' => 'test-v1',
        'text-generation.roles.classifier.provider' => 'openrouter',
        'text-generation.roles.classifier.model' => 'openrouter/auto',
        'text-generation.roles.classifier.timeout' => 12,
        'text-generation.roles.classifier.fallbacks' => [
            ['provider' => 'groq', 'model' => 'llama-test', 'timeout' => 7],
        ],
    ]);
});

test('text roles resolve provider model and fallback config', function () {
    $profile = app(TextRoleManager::class)->resolve(TextGenerationRole::Classifier);

    expect($profile->role)->toBe(TextGenerationRole::Classifier)
        ->and($profile->configVersion)->toBe('test-v1')
        ->and($profile->candidates)->toBe([
            ['provider' => 'openrouter', 'model' => 'openrouter/auto', 'timeout' => 12],
            ['provider' => 'groq', 'model' => 'llama-test', 'timeout' => 7],
        ]);
});

test('missing role config fails before prompting', function () {
    config(['text-generation.roles.classifier.model' => null]);

    app(TextRoleManager::class)->resolve(TextGenerationRole::Classifier);
})->throws(TextGenerationRoleException::class, 'model');

test('role generation falls back to the next configured provider', function () {
    AnonymousAgent::fake(function (string $prompt, $attachments, $provider, string $model) {
        if ($provider->name() === 'openrouter') {
            throw new RuntimeException('primary down');
        }

        return "Generated by {$provider->name()} using {$model}: {$prompt}";
    });

    $result = app(TextRoleManager::class)->generate(TextGenerationRequest::make(
        TextGenerationRole::Classifier,
        'Classify this company.',
        ['industry' => 'countertops'],
    ));

    expect($result->text)->toContain('Generated by groq using llama-test')
        ->and($result->provider)->toBe('groq')
        ->and($result->model)->toBe('llama-test')
        ->and($result->configVersion)->toBe('test-v1');

    AnonymousAgent::assertPrompted(fn ($prompt): bool => str_contains($prompt->prompt, '"industry": "countertops"'));
});

test('role responses can be faked through the app contract', function () {
    $fake = TextRoleManager::fake([
        TextGenerationRole::AdvisorAnswer->value => 'Use a payroll provider before employee one starts.',
    ])->preventStrayPrompts();

    $result = app(TextRoleGenerator::class)->generate(TextGenerationRequest::make(
        TextGenerationRole::AdvisorAnswer,
        'What should I do before hiring?',
    ));

    expect($result->text)->toBe('Use a payroll provider before employee one starts.')
        ->and($result->provider)->toBe('fake');

    $fake->assertGenerated(TextGenerationRole::AdvisorAnswer)
        ->assertNotGenerated(TextGenerationRole::BrandCopy);
});

test('marketing roles include the human voice guidance', function () {
    AnonymousAgent::fake(['human copy']);

    app(TextRoleManager::class)->generate(TextGenerationRequest::make(
        TextGenerationRole::BrandCopy,
        'Write a homepage tagline.',
    ));

    AnonymousAgent::assertPrompted(fn ($prompt): bool => str_contains($prompt->agent->instructions(), 'Human voice guidance')
        && str_contains($prompt->agent->instructions(), 'Avoid inflated AI-style words'));
});
